### ISSUE TITLE
Smart Components Unit Tests should be covered - Core 1.0.0 Migration

### ISSUE THREAD

**Issue by faival** [LiskHQ/lisk-hub#1015]
### Expected behaviour
- child of #996 and *parent*
- [x] Enable Unit tests for search related components - Core 1.0.0 Migration #1072 
- [x] Enable unit tests L.23 to L.43 - Core 1.0.0 Migration #1076
- [x] Enable unit tests L.44 to L.54 - Core 1.0.0 Migration #1080
- [x] Enable components unit tests L.55 to L.75 - Core 1.0.0 Migration #1082 
- [x] Enable components unit tests L.76 to L.96 - Core 1.0.0 Migration #1085
- [x] Enable components unit tests L.97 to L.118 - Core 1.0.0 Migration #1087
- [x] Enable components unit tests L.119 to L.140 - Core 1.0.0 Migration #1089
- [x] Enable components unit tests L144-L163 - Core 1.0.0 Migration #1096
