### ISSUE TITLE
Update to Lisk Core and Lisk Elements 1.0.0

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#812]
### Expected behaviour
Lisk Hub should work with Lisk Core and Lisk Elements 1.0.0

It should be done in the subtasks to make pass e2e tests in:
- [x] test/e2e/login.feature:Feature: Login page https://github.com/LiskHQ/lisk-hub/issues/937

- [x] test/e2e/send.feature:Feature: Send dialog - #967
- [x] test/e2e/explorer.feature:Feature: Explorer page - #939 
- [x] test/e2e/registerDelegate.feature:Feature: Register delegate - #940
- [x] test/e2e/registerSecondPassphrase.feature:Feature: Register second passphrase - #968
- [x] test/e2e/voting.feature:Feature: Voting page - #969
- [x] API independant features: - #941 
  - test/e2e/onboarding.feature:Feature: Onboarding
  - test/e2e/followedAccounts.feature:Feature: Followed Accounts
  - test/e2e/settings.feature:Feature: Settings dialog
- [x] Fix savedAccounts e2e tests *medium #991 
- [x] Fix explorer transaction details e2e - Core 1.0 migration #995
- [x] SignMessage.feature should pass e2e tests - Core 1.0.0 Migration #1019
- [x] Locking an account should have e2e tests - Core 1.0.0 Migration #1022
- [x] Hub should use most up-to-date rc. version of core - Core 1.0.0 Migration #1024

### Actual behaviour
Lisk Hub doesn't work with Lisk Core and Lisk Elements 1.0.0, because they have a new API.

### Steps to reproduce
The changes should be very similar to what was done in https://github.com/LiskHQ/lisk-nano/pull/1032, https://github.com/LiskHQ/lisk-nano/pull/1075 and https://github.com/LiskHQ/lisk-nano/pull/1073
