### ISSUE TITLE
Unit and Integration tests should meet coverage thresholds - Core 1.0.0 migration

### ISSUE THREAD

**Issue by faival** [LiskHQ/lisk-hub#996]
### Expected behaviour
- [x] Provide commented glob patterns to run UTests - Core 1.0.0 Migration #1028

#### Integration
- [x] AccountSwitch integration tests should be covered - Core 1.0.0 Migration #997 
- [x] AccountTransactions integration tests should be covered - Core 1.0.0 Migration #998
- [x] Dashboard integration tests should be covered - Core 1.0.0 Migration #999
- [x] Login integration tests should be covered - Core 1.0.0 Migration #1000
- [x] Register integration tests should be covered - Core 1.0.0 Migration #1001
- [x] RegisterDelegate integration tests should be covered - Core 1.0.0 Migration #1002
- [x] TransactionId integration tests should be covered - Core 1.0.0 Migration #1003
- [x] Voting integration tests should be covered - Core 1.0.0 Migration #1004
- [x] Wallet integration tests should be covered - Core 1.0.0 Migration #1005

#### Redux Actions
- [x] Account, Delegate, Dialog, followedAccounts Actions Unit Tests should be covered - Core 1.0.0 Migration #1006
- [x] Loading, peers, savedAccounts, settings Actions Unit Tests should be covered - Core 1.0.0 Migration #1007
- [x] Toaster, transactions, voting Actions Unit Tests should be covered - Core 1.0.0 Migration #1008
#### Redux Reducers
- [x] Account, delegate, dialog, followedAccounts, Reducers Unit Tests should be covered - Core 1.0.0 Migration #1009
- [x] Loading, peers, savedAccounts, search, Reducers Unit Tests should be covered - Core 1.0.0 Migration #1010
- [x] Settings, toaster, transaction, transactions, voting, Reducers Unit Tests should be covered - Core 1.0.0 Migration #1011

#### Redux Middlewares
- [x] Account, followedAccounts, loadingBar, login, Middlewares Unit Tests should be covered - Core 1.0.0 Migration #1012
- [x] Notification, offline, peers, savedAccounts, Middlewares Unit Tests should be covered - Core 1.0.0 Migration #1013
- [x] SavedSettings, socket, voting, Middlewares Unit Tests should be covered - Core 1.0.0 Migration #1014

#### Smart Components
- [x] Smart Components Unit Tests should be covered - Core 1.0.0 Migration #1015

#### Coverage thresholds
- [x] Coverage thresholds should pass Part 1 - Core 1.0.0 Migration #1110 
- [x] Coverage thresholds should pass Part 2 - Core 1.0.0 Migration #1111
- [x] Coverage thresholds should pass Part 3 - Core 1.0.0 Migration #1112
